Improved error handling in asset validator (#446)
Some minor improvements to this tool both for contributors who may be working with it and for end-users making PRs to `bevy-assets`

- Show a friendlier error when failing to specify the `bevy-assets` path as a cli argument
- Show an error if the user specifies the `bevy-assets` path incorrectly
- Show errors that occur during `parse_assets`
- Check that images exist
- Group errors by asset

I felt a bit awkward working around the `AssetValidator` trait, and I'm not super strong with rust error handling / `anyhow` so any feedback would be appreciated.

Now outputs something like

```
(a bunch of metadata spam)

UnFlock
  DescriptionWithFormatting

taipo
  DescriptionTooLong
  ImageInvalidLink

Error: 2 asset(s) are invalid.
```

The change to `lib.rs` is much smaller than it looks. It consists of:
- removing a level of indentation by exiting early
- allowing `fs::read_dir` to potentially fail rather than hiding it behind `is_dir`
- removing the unwrap from `toml::from_str` in favor of `?`